
import json, pathlib

# TODO: Support other valid spellings of terms? e.g. "centre" for "center"
#       The basic spelling correction, with its current parameters,
#       should accept most of these alternate valid spellings.

# using, e.g., ME(R), is not supported, but leaving it here
neuropils = [
        (['ME(R)', 'ME(L)'],
            ['medulla', 'med', 'me']),
        ('ME(R)',
            ['right medulla', 'right med', 'med_r', 'right me', 'ME(R)']),
        ('ME(L)',
            ['left medulla', 'left med', 'med_l',  'left me', 'ME(L)']),
        (['AME(R)', 'AME(L)'],
            ['accessory medulla', 'ame']),
        ('AME(R)',
            ['right accessory medulla', 'right ame', 'ame_r', 'AME(R)']),
        ('AME(L)',
            ['left accessory medulla', 'left ame', 'ame_l', 'AME(L)']),
        (['LO(R)', 'LO(L)'],
            ['lobula', 'lob', 'lo']),
        ('LO(R)',
            ['right lobula', 'right lob', 'lob_r', 'lo_r', 'right lo', 'LO(R)']),
        ('LO(L)',
            ['left lobula', 'left lob', 'lob_l', 'lo_l', 'right lo', 'LO(L)']),
        (['LOP(R)', 'LOP(L)'],
            ['lobula plate', 'lop']),
        ('LOP(R)',
            ['right lobula plate', 'right lop', 'lop_r', 'LOP(R)']),
        ('LOP(L)',
            ['left lobula plate', 'left lop', 'lop_l', 'LOP(L)']),
        (['AL(R)', 'AL(L)'],
            ['antennal lobe', 'al']),
        ('AL(R)',
            ['right antennal lobe', 'right al', 'al_r', 'AL(R)']),
        ('AL(L)',
            ['left antennal lobe', 'left al', 'al_l', 'AL(L)']),
        (['AN(R)', 'AN(L)'],
            ['antenna', 'an']),
        ('AN(R)',
            ['right antenna', 'right an', 'an_r', 'AN(R)']),
        ('AN(L)',
            ['left antenna', 'left an', 'an_l', 'AN(L)']),
        (['EB', 'PB', 'FB', 'NO(R)', 'NO(L)', 'AB(R)', 'AB(L)'],
            ['central complex', 'cc', 'cx']),
        ('EB',
            ['ellipsoid body', 'right ellipsoid body', 'left ellipsoid body', 'eb_r', 'eb_l', 'eb']),
        (['LH(R)', 'LH(L)'],
            ['lateral horn', 'lh']),
        ('LH(R)',
            ['right lateral horn', 'right lh', 'lh_r', 'LH(R)']),
        ('LH(L)',
            ['left lateral horn', 'left lh', 'lh_l', 'LH(L)']),
        (['MB(R)', 'MB(L)'],
            ['mushroom body', 'mb']),
        ('MB(R)',
            ['right mushroom body', 'right mb', 'mb_r', 'MB(R)']),
        ('MB(L)',
            ['left mushroom body', 'left mb', 'mb_l', 'MB(L)']),
        (['NO(R)', 'NO(L)'],
            ['noduli', 'nod', 'no']),
        ('NO(R)',
            ['right nodulus', 'right nod', 'right no', 'nod_r', 'no_r', 'NO(R)']),
        ('NO(L)',
            ['left nodulus', 'left nod', 'left no', 'nod_l', 'no_l', 'NO(L)']),
        ('PB',
            ['protocerebral bridge', 'pcb', 'pb',
             'right protocerebral bridge', 'right pcb', 'right pb', 'pcb_r', 'pb_r',
             'left protocerebral bridge', 'left pcb', 'left pb', 'pcb_l', 'pb_l']),
        ('AB(R)',
            ['right asymmetrical body', 'ab_r', 'right ab', 'AB(R)']),
        ('AB(L)',
            ['left asymmetrical body', 'ab_l', 'left ab', 'AB(L)']),
        (['AB(L)', 'AB(R)'],
            ['asymmetrical body', 'ab']),
        ('FB',
            ['fanshaped body', 'fb',
             'right fanshaped body', 'right fb', 'fb_r',
             'left fanshaped body', 'left fb', 'fb_l']),
        (['AL(R)', 'AL(L)', 'LH(R)', 'LH(L)', 'MB(R)', 'MB(L)'],
            ['olfactory']),
        ('AVLP(R)',
            ['right anterior ventrolateral protocerebrum', 'right avlp', 'avlp_r', 'AVLP(R)']),
        ('AVLP(L)',
            ['left anterior ventrolateral protocerebrum', 'left avlp', 'avlp_l', 'AVLP(L)']),
        (['AVLP(R)', 'AVLP(L)'],
            ['anterior ventrolateral protocerebrum', 'avlp', 'avlp_r']),
        ('PVLP(R)',
            ['right posterior ventrolateral protocerebrum', 'right pvlp', 'pvlp_r', 'PVLP(R)']),
        ('PVLP(L)',
            ['left posterior ventrolateral protocerebrum', 'left pvlp', 'pvlp_l', 'PVLP(L)']),
        (['PVLP(R)', 'PVLP(L)'],
            ['posterior ventrolateral protocerebrum', 'pvlp', 'pvlp_r']),
        (['AVLP(R)', 'PVLP(R)'],
            ['right ventrolateral protocerebrum', 'right vlp', 'vlp_r']),
        (['AVLP(L)', 'PVLP(L)'],
            ['left ventrolateral protocerebrum', 'left vlp', 'vlp_l']),
        (['AVLP(R)', 'PVLP(R)', 'AVLP(L)', 'PVLP(L)'],
            ['ventrolateral protocerebrum', 'vlp']),
        (['AOTU(R)', 'AOTU(L)'],
            ['anterior optic tubercle', 'aotu']),
        ('AOTU(R)',
            ['right anterior optic tubercle', 'right aotu', 'aotu_r', 'AOTU(R)']),
        ('AOTU(L)',
            ['left anterior optic tubercle', 'left aotu', 'aotu_l', 'AOTU(L)']),
        (['BU(R)', 'BU(L)'],
            ['bulb', 'bu']),
        ('BU(R)',
            ['right bulb', 'right bu' 'bu_r', 'BU(R)']),
        ('BU(L)',
            ['left bulb', 'left bu', 'bu_l', 'BU(L)']),
        (['LAL(R)', 'LAL(L)'],
            ['lateral accessory lobe', 'lal']),
        ('LAL(R)',
            ['right lateral accessory lobe', 'right lal', 'lal_r', 'LAL(R)']),
        ('LAL(L)',
            ['left lateral accessory lobe', 'left lal', 'lal_l', 'LAL(L)']),
        ('PLP(R)',
            ['right posterior lateral protocerebrum', 'right plp', 'plp_r', 'PLP(R)']),
        ('PLP(L)',
            ['left posterior lateral protocerebrum', 'left plp', 'plp_l', 'PLP(L)']),
        (['PLP(R)','PLP(L)'],
            ['posterior lateral protocerebrum', 'plp']),
        ('WED(R)',
            ['right wedge', 'right wed', 'wed_r', 'WED(R)']),
        ('WED(L)',
            ['left wedge', 'left wed', 'wed_l', 'WED(L)']),
        (['WED(R)','WED(L)'],
            ['wedge', 'wed']),
        (['SLP(R)', 'SLP(L)'],
            ['superior lateral protocebrebrum', 'slp']),
        ('SLP(R)',
            ['right superior lateral protocebrebrum', 'right slp', 'slp_r', 'SLP(R)']),
        ('SLP(L)',
            ['left superior lateral protocebrebrum', 'left slp', 'slp_l', 'SLP(L)']),
        (['SIP(R)', 'SIP(L)'],
            ['superior intermediate protocebrebrum', 'sip']),
        ('SIP(R)',
            ['right superior intermediate protocebrebrum', 'right sip', 'sip_r', 'SIP(R)']),
        ('SIP(L)',
            ['left superior intermediate protocebrebrum', 'left sip', 'sip_l', 'SIP(L)']),
        (['SMP(R)', 'SMP(L)'],
            ['superior medial protocebrebrum', 'smp']),
        ('SMP(R)',
            ['right superior medial protocebrebrum', 'right smp', 'smp_r', 'SMP(R)']),
        ('SMP(L)',
            ['left superior medial protocebrebrum', 'left smp', 'smp_l', 'SMP(L)']),
        (['CRE(R)', 'CRE(L)'],
            ['crepine', 'cre']),
        ('CRE(R)',
            ['right crepine', 'right cre', 'cre_r', 'CRE(R)']),
        ('CRE(L)',
            ['left crepine', 'left cre', 'cre_l', 'CRE(L)']),
        (['SCL(R)', 'SCL(L)'],
            ['superior clamp', 'scl']),
        ('SCL(R)',
            ['right superior clamp', 'right scl', 'scl_r', 'SCL(R)']),
        ('SCL(L)',
            ['left superior clamp', 'left scl', 'scl_l', 'SCL(L)']),
        (['ICL(R)', 'ICL(L)'],
            ['interior clamp', 'icl']),
        ('ICL(R)',
            ['right interior clamp', 'right icl', 'icl_r', 'ICL(R)']),
        ('ICL(L)',
            ['left interior clamp', 'left icl', 'icl_l', 'ICL(L)']),
        ('IB',
            ['interior bridge', 'ib']),
        (['ATL(R)', 'ATL(L)'],
            ['antler', 'atl']),
        ('ATL(R)',
            ['right antler', 'right atl', 'atl_r', 'ATL(R)']),
        ('ATL(L)',
            ['left antler', 'left atl', 'atl_l', 'ATL(L)']),
        (['VES(R)', 'VES(L)'],
            ['vest', 'ves']),
        ('VES(R)',
            ['right vest', 'right ves', 'ves_r', 'VES(R)']),
        ('VES(L)',
            ['left vest', 'left ves', 'ves_l', 'VES(L)']),
        (['EPA(R)', 'EPA(L)'],
            ['epaulette', 'epa']),
        ('EPA(R)',
            ['right epaulette', 'right epa', 'ves_r', 'EPA(R)']),
        ('EPA(L)',
            ['left epaulette', 'left epa', 'ves_l', 'EPA(L)']),
        (['GOR(R)', 'GOR(L)'],
            ['gorget', 'gor']),
        ('GOR(R)',
            ['right gorget', 'right gor', 'gor_r', 'GOR(R)']),
        ('GOR(L)',
            ['left gorget', 'left gor', 'gor_l', 'GOR(L)']),
        (['SPS(R)', 'SPS(L)'],
            ['superior posterior slope', 'sps']),
        ('SPS(R)',
            ['right superior posterior slope', 'right sps', 'sps_r', 'SPS(R)']),
        ('SPS(L)',
            ['left superior posterior slope', 'left sps', 'sps_l', 'SPS(L)']),
        (['IPS(R)', 'IPS(L)'],
            ['inferior posterior slope', 'ips']),
        ('IPS(R)',
            ['right inferior posterior slope', 'right ips', 'ips_r', 'IPS(R)']),
        ('IPS(L)',
            ['left inferior posterior slope', 'left ips', 'ips_l', 'IPS(L)']),
        (['SAD(R)', 'SAD(L)'],
            ['saddle', 'sad']),
        ('SAD(R)',
            ['right saddle', 'right sad', 'sad_r', 'SAD(R)']),
        ('SAD(L)',
            ['left saddle', 'left sad', 'sad_l', 'SAD(L)']),
        (['FLA(R)', 'FLA(L)'],
            ['flange', 'fla']),
        ('FLA(R)',
            ['right flange', 'right fla', 'fla_r', 'FLA(R)']),
        ('FLA(L)',
            ['left flange', 'left fla', 'fla_l', 'FLA(L)']),
        (['CAN(R)', 'CAN(L)'],
            ['cantle', 'can']),
        ('CAN(R)',
            ['right cantle', 'right can', 'can_r', 'CAN(R)']),
        ('CAN(L)',
            ['left cantle', 'left can', 'can_l', 'CAN(L)']),
        (['PRW(R)', 'PRW(L)'],
            ['prow', 'can']),
        ('PRW(R)',
            ['right prow', 'right prw', 'prw_r', 'PRW(R)']),
        ('PRW(L)',
            ['left prow', 'left prw', 'prw_l', 'PRW(L)']),
        (['ME(R)', 'AME(R)', 'LO(R)', 'LOP(R)'],
            ['right optic lobe', 'right ol', 'ol_r']),
        (['ME(L)', 'AME(L)', 'LO(L)', 'LOP(L)'],
            ['left optic lobe', 'left ol', 'ol_l']),
        (['ME(R)', 'AME(R)', 'LO(R)', 'LOP(R)','ME(L)', 'AME(L)', 'LO(L)', 'LOP(L)'],
            ['optic lobe', 'ol']),
        (['BU(R)', 'LAL(R)'],
            ['right lateral complex', 'right lx', 'lx_r']),
        (['BU(L)', 'LAL(L)'],
            ['left lateral complex', 'left lx', 'lx_l']),
        (['BU(R)', 'LAL(R)', 'BU(L)', 'LAL(L)'],
            ['lateral complex', 'lx']),
        (['AOTU(R)', 'AVLP(R)', 'PVLP(R)', 'PLP(R)', 'WED(R)'],
            ['right ventrolateral neuropils', 'right vlnp', 'vlnp_r']),
        (['AOTU(R)', 'AVLP(R)', 'PVLP(R)', 'PLP(R)', 'WED(R)'],
            ['right ventrolateral neuropils', 'right vlnp', 'vlnp_r']),
        (['AOTU(L)', 'AVLP(L)', 'PVLP(L)', 'PLP(L)', 'WED(L)'],
            ['left ventrolateral neuropils', 'left vlnp', 'vlnp_l']),
        (['AOTU(L)', 'AVLP(L)', 'PVLP(L)', 'PLP(L)', 'WED(L)', 'AOTU(R)', 'AVLP(R)', 'PVLP(R)', 'PLP(R)', 'WED(R)'],
            ['ventrolateral neuropils', 'vlnp']),
        (['SLP(R)', 'SIP(R)', 'SMP(R)'],
            ['right superior neuropils', 'right snp', 'snp_r']),
        (['SLP(L)', 'SIP(L)', 'SMP(L)'],
            ['left superior neuropils', 'left snp', 'snp_l']),
        (['SLP(R)', 'SIP(R)', 'SMP(R)', 'SLP(L)', 'SIP(L)', 'SMP(L)'],
            ['superior neuropils', 'snp']),
        (['CRE(R)', 'SCL(R)', 'ICL(R)', 'IB(R)', 'ATL(R)'],
            ['right inferior neuropils', 'right inp', 'inp_r']),
        (['CRE(L)', 'SCL(L)', 'ICL(L)', 'IB(L)', 'ATL(L)'],
            ['left inferior neuropils', 'left inp', 'inp_l']),
        (['CRE(R)', 'SCL(R)', 'ICL(R)', 'IB(R)', 'ATL(R)', 'CRE(L)', 'SCL(L)', 'ICL(L)', 'IB(L)', 'ATL(L)'],
            ['inferior neuropils', 'inp']),
        (['VES(R)', 'EPA(R)', 'GOR(R)', 'SPS(R)', 'IPS(R)'],
            ['right ventromedial neuropils', 'right vmnp', 'vmnp_r']),
        (['VES(L)', 'EPA(L)', 'GOR(L)', 'SPS(L)', 'IPS(L)'],
            ['left ventromedial neuropils', 'left vmnp', 'vmnp_l']),
        (['VES(R)', 'EPA(R)', 'GOR(R)', 'SPS(R)', 'IPS(R)', 'VES(L)', 'EPA(L)', 'GOR(L)', 'SPS(L)', 'IPS(L)'],
            ['ventromedial neuropils', 'vmnp']),
        (['SAD(R)', 'FLA(R)', 'CAN(R)', 'PRW(R)'],
            ['right periesophageal neuropils', 'right penp', 'penp_r']),
        (['SAD(L)', 'FLA(L)', 'CAN(L)', 'PRW(L)'],
            ['left periesophageal neuropils', 'left penp', 'penp_l']),
        (['SAD(R)', 'FLA(R)', 'CAN(R)', 'PRW(R)', 'SAD(L)', 'FLA(L)', 'CAN(L)', 'PRW(L)'],
            ['periesophageal neuropils', 'penp']),
    ]

arborization_regions = [('CA(R)', ['right calyx', 'right ca', 'ca_r']),
                        ('CA(L)', ['left calyx', 'left ca', 'ca_l']),
                        (['CA(R)', 'CA(L)'], ['calyx', 'ca']),
                        ('lACA(R)', ['right laca', 'right lateral accessory calyx', 'laca_r']),
                        ('lACA(L)', ['left laca', 'left lateral accessory calyx', 'laca_l']),
                        (['lACA(R)', 'lACA(L)'], ['laca', 'lateral accessory calyx']),
                        ('dACA(R)', ['right daca', 'right dorsal accessory calyx', 'daca_r']),
                        ('dACA(L)', ['left daca', 'left dorsal accessory calyx', 'daca_l']),
                        (['dACA(R)', 'dACA(L)'], ['daca', 'dorsal accessory calyx']),
                        ('vACA(R)', ['right vaca', 'right ventral accessory calyx', 'vaca_r']),
                        ('dACA(L)', ['left vaca', 'left ventral accessory calyx', 'vaca_l']),
                        (['vACA(R)', 'vACA(L)'], ['vaca', 'ventral accessory calyx']),
                        ('PED(R)', ['right ped', 'right pedunculus', 'ped_r']),
                        ('PED(L)', ['left ped', 'left pedunculus', 'ped_l']),
                        (['PED(R)', 'PED(L)'], ['ped', 'pedunculus']),
                        ('aL(R)', ['right alpha lobe']),
                        ('aL(L)', ['left alpha lobe']),
                        (['aL(R)', 'aL(L)'], ['alpha lobe']),
                        ('a1(R)', ['right alpha lobe compartment 1', 'right alpha1 compartment', "alpha1_r"]),
                        ('a2(R)', ['right alpha lobe compartment 2', 'right alpha2 compartment', "alpha2_r"]),
                        ('a3(R)', ['right alpha lobe compartment 3', 'right alpha3 compartment', "alpha3_r"]),
                        ('a1(L)', ['left alpha lobe compartment 1', 'left alpha1 compartment', "alpha1_l"]),
                        ('a2(L)', ['left alpha lobe compartment 2', 'left alpha2 compartment', "alpha2_l"]),
                        ('a3(L)', ['left alpha lobe compartment 3', 'left alpha3 compartment', "alpha3_l"]),
                        (['a1(R)','a1(L)'], ['alpha lobe compartment 1', 'alpha1 compartment', "alpha1"]),
                        (['a2(R)','a2(L)'], ['alpha lobe compartment 2', 'alpha2 compartment', "alpha2"]),
                        (['a3(R)','a3(L)'], ['alpha lobe compartment 3', 'alpha3 compartment', "alpha3"]),
                        ("a'L(R)", ['right alpha prime lobe', "right alpha' lobe"]),
                        ("a'L(L)", ['left alpha prime lobe', "left alpha' lobe"]),
                        (["a'L(R)", "a'L(L)"], ['alpha prime lobe', "alpha' lobe"]),
                        ("a'1(R)", ['right alpha prime lobe compartment 1', "right alpha'1 compartment", "alpha'1_r"]),
                        ("a'2(R)", ['right alpha prime lobe compartment 2', "right alpha'2 compartment", "alpha'2_r"]),
                        ("a'3(R)", ['right alpha prime lobe compartment 3', "right alpha'3 compartment", "alpha'3_r"]),
                        ("a'1(L)", ['left alpha prime lobe compartment 1', "left alpha'1 compartment", "alpha'1_l"]),
                        ("a'2(L)", ['left alpha prime lobe compartment 2', "left alpha'2 compartment", "alpha'2_l"]),
                        ("a'3(L)", ['left alpha prime lobe compartment 3', "left alpha'3 compartment", "alpha'3_l"]),
                        (["a'1(R)","a'1(L)"], ['alpha prime lobe compartment 1', "alpha'1 compartment", "alpha'1"]),
                        (["a'2(R)","a'2(L)"], ['alpha prime lobe compartment 2', "alpha'2 compartment", "alpha'2"]),
                        (["a'3(R)","a'3(L)"], ['alpha prime lobe compartment 3', "alpha'3 compartment", "alpha'3"]),
                        ('bL(R)', ['right beta lobe']),
                        ('bL(L)', ['left beta lobe']),
                        (['bL(R)', 'bL(L)'], ['beta lobe']),
                        ('b1(R)', ['right beta lobe compartment 1', 'right beta1 compartment', "beta1_l"]),
                        ('b2(R)', ['right beta lobe compartment 2', 'right beta2 compartment', "beta2_r"]),
                        ('b1(L)', ['left beta lobe compartment 1', 'left beta1 compartment', "beta1_l"]),
                        ('b2(L)', ['left beta lobe compartment 2', 'left beta2 compartment', "beta2_l"]),
                        (['b1(R)','b1(L)'], ['beta lobe compartment 1', 'beta1 compartment', "beta1"]),
                        (['b2(R)','b2(L)'], ['beta lobe compartment 2', 'beta2 compartment', "beta2"]),
                        ("b'L(R)", ['right beta prime lobe', "right beta' lobe"]),
                        ("b'L(L)", ['left beta prime lobe', "left beta' lobe"]),
                        (["b'L(R)", "b'L(L)"], ['beta prime lobe', "beta' lobe"]),
                        ("b'1(R)", ['right beta prime lobe compartment 1', "right beta'1 compartment", "beta'1_r"]),
                        ("b'2(R)", ['right beta prime lobe compartment 2', "right beta'2 compartment", "beta'2_r"]),
                        ("b'1(L)", ['left beta prime lobe compartment 1', "left beta'1 compartment", "beta'1_l"]),
                        ("b'2(L)", ['left beta prime lobe compartment 2', "left beta'2 compartment", "beta'2_l"]),
                        (["b'1(R)","b'1(L)"], ['beta prime lobe compartment 1', "beta'1 compartment", "beta'1"]),
                        (["b'2(R)","b'2(L)"], ['beta prime lobe compartment 2', "beta'2 compartment", "beta'2"]),
                        ('gL(R)', ['right gamma lobe']),
                        ('gL(L)', ['left gamma lobe']),
                        (['gL(R)', 'gL(L)'], ['gamma lobe']),
                        ('g1(R)', ['right gamma lobe compartment 1', 'right gamma1 compartment', 'gamma1_r']),
                        ('g2(R)', ['right gamma lobe compartment 2', 'right gamma2 compartment', 'gamma2_r']),
                        ('g3(R)', ['right gamma lobe compartment 3', 'right gamma3 compartment', 'gamma3_r']),
                        ('g4(R)', ['right gamma lobe compartment 4', 'right gamma4 compartment', 'gamma4_r']),
                        ('g5(R)', ['right gamma lobe compartment 5', 'right gamma5 compartment', 'gamma5_r']),
                        ('g1(L)', ['left gamma lobe compartment 1', 'left gamma1 compartment', 'gamma1_l']),
                        ('g2(L)', ['left gamma lobe compartment 2', 'left gamma2 compartment', 'gamma2_l']),
                        ('g3(L)', ['left gamma lobe compartment 3', 'left gamma3 compartment', 'gamma3_l']),
                        ('g4(L)', ['left gamma lobe compartment 4', 'left gamma4 compartment', 'gamma4_l']),
                        ('g5(L)', ['left gamma lobe compartment 5', 'left gamma5 compartment', 'gamma5_l']),
                        (['g1(R)','g1(L)'], ['gamma lobe compartment 1', 'gamma1 compartment', 'gamma1']),
                        (['g2(R)','g2(L)'], ['gamma lobe compartment 2', 'gamma2 compartment', 'gamma2']),
                        (['g3(R)','g3(L)'], ['gamma lobe compartment 3', 'gamma3 compartment', 'gamma3']),
                        (['g4(R)','g4(L)'], ['gamma lobe compartment 4', 'gamma4 compartment', 'gamma4']),
                        (['g5(R)','g5(L)'], ['gamma lobe compartment 5', 'gamma5 compartment', 'gamma5']),
                        ('GA(R)', ['right gall', 'right ga', 'ga_r']),
                        ('GA(L)', ['left gall', 'left ga', 'ga_l']),
                        (['GA(R)','GA(L)'], ['gall', 'ga']),
                        ('FBl1', ['fanshaped body layer 1', 'fb layer 1', 'fbl1']),
                        ('FBl2', ['fanshaped body layer 2', 'fb layer 2', 'fbl2']),
                        ('FBl3', ['fanshaped body layer 3', 'fb layer 3', 'fbl3']),
                        ('FBl4', ['fanshaped body layer 4', 'fb layer 4', 'fbl4']),
                        ('FBl5', ['fanshaped body layer 5', 'fb layer 5', 'fbl5']),
                        ('FBl6', ['fanshaped body layer 6', 'fb layer 6', 'fbl6']),
                        ('FBl7', ['fanshaped body layer 7', 'fb layer 7', 'fbl7']),
                        ('FBl8', ['fanshaped body layer 8', 'fb layer 8', 'fbl8']),
                        ('FBl9', ['fanshaped body layer 9', 'fb layer 9', 'fbl9']),
                        ('EBr1', ['ellipsoid body zone r1', 'ebr1', 'eb zone r1']),
                        ('EBr2r4', ['ellipsoid body zone r2r4', 'ebr2r4', 'eb zone r2r4']),
                        ('EBr3am', ['ellipsoid body zone r3am', 'ebr3am', 'eb zone r3am']),
                        ('EBr3d', ['ellipsoid body zone r3d', 'ebr3d', 'eb zone r3d']),
                        ('EBr3pw', ['ellipsoid body zone r3pw', 'ebr3pw', 'eb zone r3pw']),
                        ('EBr5', ['ellipsoid body zone r5', 'ebr5', 'eb zone r5']),
                        ('EBr6', ['ellipsoid body zone r6', 'ebr6', 'eb zone r6']),
                        ('PB(R1)', ['pb glomerulus r1', 'pb r1', 'pbr1']),
                        ('PB(R2)', ['pb glomerulus r2', 'pb r2', 'pbr2']),
                        ('PB(R3)', ['pb glomerulus r3', 'pb r3', 'pbr3']),
                        ('PB(R4)', ['pb glomerulus r4', 'pb r4', 'pbr4']),
                        ('PB(R5)', ['pb glomerulus r5', 'pb r5', 'pbr5']),
                        ('PB(R6)', ['pb glomerulus r6', 'pb r6', 'pbr6']),
                        ('PB(R7)', ['pb glomerulus r7', 'pb r7', 'pbr7']),
                        ('PB(R8)', ['pb glomerulus r8', 'pb r8', 'pbr8']),
                        ('PB(R9)', ['pb glomerulus r9', 'pb r9', 'pbr9']),
                        ('PB(L1)', ['pb glomerulus l1', 'pb l1', 'pbl1']),
                        ('PB(L2)', ['pb glomerulus l2', 'pb l2', 'pbl2']),
                        ('PB(L3)', ['pb glomerulus l3', 'pb l3', 'pbl3']),
                        ('PB(L4)', ['pb glomerulus l4', 'pb l4', 'pbl4']),
                        ('PB(L5)', ['pb glomerulus l5', 'pb l5', 'pbl5']),
                        ('PB(L6)', ['pb glomerulus l6', 'pb l6', 'pbl6']),
                        ('PB(L7)', ['pb glomerulus l7', 'pb l7', 'pbl7']),
                        ('PB(L8)', ['pb glomerulus l8', 'pb l8', 'pbl8']),
                        ('PB(L9)', ['pb glomerulus l9', 'pb l9', 'pbl9']),
                        ('NO1(R)', ['right nodulus 1', 'right no1', 'no1_r']),
                        ('NO2(R)', ['right nodulus 2', 'right no2', 'no2_r']),
                        ('NO3(R)', ['right nodulus 3', 'right no3', 'no3_r']),
                        ('NO1(L)', ['left nodulus 1', 'left no1', 'no1_l']),
                        ('NO2(L)', ['left nodulus 2', 'left no2', 'no2_l']),
                        ('NO3(L)', ['left nodulus 3', 'left no3', 'no3_l']),
                        (['NO1(R)','NO1(L)'], ['noduli 1', 'no1']),
                        (['NO2(R)','NO2(L)'], ['noduli 2', 'no2']),
                        (['NO3(R)','NO3(L)'], ['noduli 3', 'no3']),
                        ('RUB(R)', ['right rub', 'right rubus', 'rub_r']),
                        ('RUB(L)', ['left rub', 'left rubus', 'rub_l']),
                        (['RUB(R)','RUB(L)'], ['rub', 'rubus']),
                        ('ROB(R)', ['right round body', 'right rob', 'rob_r']),
                        ('ROB(L)', ['left round body', 'left rob', 'rob_l']),
                        (['ROB(R)','ROB(L)'], ['round body', 'rob']),
                        ('AMMC', ['antennal mechanosensory and motor center', 'ammc']),
                        ('AL-DA1(R)', ['right DA1 glomerulus']),
                        (['AL-DA1(R)', 'AL-DA1(L)'], ['DA1 glomerulus']),
                        ('AL-DA2(R)', ['right DA2 glomerulus']),
                        ('AL-DA2(L)', ['left DA2 glomerulus']),
                        (['AL-DA2(R)', 'AL-DA2(L)'], ['DA2 glomerulus']),
                        ('AL-DA3(R)', ['right DA3 glomerulus']),
                        ('AL-DA3(L)', ['left DA3 glomerulus']),
                        (['AL-DA3(R)', 'AL-DA3(L)'], ['DA3 glomerulus']),
                        ('AL-DA4l(R)', ['right DA4l glomerulus']),
                        ('AL-DA4l(L)', ['left DA4l glomerulus']),
                        (['AL-DA4l(R)', 'AL-DA4l(L)'], ['DA4l glomerulus']),
                        ('AL-DA4m(R)', ['right DA4m glomerulus']),
                        ('AL-DA4m(L)', ['left DA4m glomerulus']),
                        (['AL-DA4m(R)', 'AL-DA4m(L)'], ['DA4m glomerulus']),
                        ('AL-DC1(R)', ['right DC1 glomerulus']),
                        ('AL-DC1(L)', ['left DC1 glomerulus']),
                        (['AL-DC1(R)', 'AL-DC1(L)'], ['DC1 glomerulus']),
                        ('AL-DC2(R)', ['right DC2 glomerulus']),
                        ('AL-DC2(L)', ['left DC2 glomerulus']),
                        (['AL-DC2(R)', 'AL-DC2(L)'], ['DC2 glomerulus']),
                        ('AL-DC3(R)', ['right DC3 glomerulus']),
                        ('AL-DC3(L)', ['left DC3 glomerulus']),
                        (['AL-DC3(R)', 'AL-DC3(L)'], ['DC3 glomerulus']),
                        ('AL-DC4(R)', ['right DC4 glomerulus']),
                        ('AL-DC4(L)', ['left DC4 glomerulus']),
                        (['AL-DC4(R)', 'AL-DC4(L)'], ['DC4 glomerulus']),
                        ('AL-DL1(R)', ['right DL1 glomerulus']),
                        ('AL-DL1(L)', ['left DL1 glomerulus']),
                        (['AL-DL1(R)', 'AL-DL1(L)'], ['DL1 glomerulus']),
                        ('AL-DL2d(R)', ['right DL2d glomerulus']),
                        ('AL-DL2d(L)', ['left DL2d glomerulus']),
                        (['AL-DL2d(R)', 'AL-DL2d(L)'], ['DL2d glomerulus']),
                        ('AL-DL2v(R)', ['right DL2v glomerulus']),
                        ('AL-DL2v(L)', ['left DL2v glomerulus']),
                        (['AL-DL2v(R)', 'AL-DL2v(L)'], ['DL2v glomerulus']),
                        ('AL-DL3(R)', ['right DL3 glomerulus']),
                        ('AL-DL3(L)', ['left DL3 glomerulus']),
                        (['AL-DL3(R)', 'AL-DL3(L)'], ['DL3 glomerulus']),
                        ('AL-DL4(R)', ['right DL4 glomerulus']),
                        ('AL-DL4(L)', ['left DL4 glomerulus']),
                        (['AL-DL4(R)', 'AL-DL4(L)'], ['DL4 glomerulus']),
                        ('AL-DL5(R)', ['right DL5 glomerulus']),
                        ('AL-DL5(L)', ['left DL5 glomerulus']),
                        (['AL-DL5(R)', 'AL-DL5(L)'], ['DL5 glomerulus']),
                        ('AL-D(R)', ['right D glomerulus']),
                        ('AL-D(L)', ['left D glomerulus']),
                        (['AL-D(R)', 'AL-D(L)'], ['D glomerulus']),
                        ('AL-DM1(R)', ['right DM1 glomerulus']),
                        ('AL-DM1(L)', ['left DM1 glomerulus']),
                        (['AL-DM1(R)', 'AL-DM1(L)'], ['DM1 glomerulus']),
                        ('AL-DM2(R)', ['right DM2 glomerulus']),
                        ('AL-DM2(L)', ['left DM2 glomerulus']),
                        (['AL-DM2(R)', 'AL-DM2(L)'], ['DM2 glomerulus']),
                        ('AL-DM3(R)', ['right DM3 glomerulus']),
                        ('AL-DM3(L)', ['left DM3 glomerulus']),
                        (['AL-DM3(R)', 'AL-DM3(L)'], ['DM3 glomerulus']),
                        ('AL-DM4(R)', ['right DM4 glomerulus']),
                        ('AL-DM4(L)', ['left DM4 glomerulus']),
                        (['AL-DM4(R)', 'AL-DM4(L)'], ['DM4 glomerulus']),
                        ('AL-DM6(R)', ['right DM6 glomerulus']),
                        ('AL-DM6(L)', ['left DM6 glomerulus']),
                        (['AL-DM6(R)', 'AL-DM6(L)'], ['DM6 glomerulus']),
                        ('AL-DM1(R)', ['right DM1 glomerulus']),
                        ('AL-DM1(L)', ['left DM1 glomerulus']),
                        (['AL-DM1(R)', 'AL-DM1(L)'], ['DM1 glomerulus']),
                        ('AL-DP1l(R)', ['right DP1l glomerulus']),
                        ('AL-DP1l(L)', ['left DP1l glomerulus']),
                        (['AL-DP1l(R)', 'AL-DP1l(L)'], ['DP1l glomerulus']),
                        ('AL-DP1m(R)', ['right DP1m glomerulus']),
                        ('AL-DP1m(L)', ['left DP1m glomerulus']),
                        (['AL-DP1m(R)', 'AL-DP1m(L)'], ['DP1m glomerulus']),
                        ('AL-VA1d(R)', ['right VA1d glomerulus']),
                        ('AL-VA1d(L)', ['left VA1d glomerulus']),
                        (['AL-VA1d(R)', 'AL-VA1d(L)'], ['VA1d glomerulus']),
                        ('AL-VA1v(R)', ['right VA1v glomerulus']),
                        ('AL-VA1v(L)', ['left VA1v glomerulus']),
                        (['AL-VA1v(R)', 'AL-VA1v(L)'], ['VA1v glomerulus']),
                        ('AL-VA2(R)', ['right VA2 glomerulus']),
                        ('AL-VA2(L)', ['left VA2 glomerulus']),
                        (['AL-VA2(R)', 'AL-VA2(L)'], ['VA2 glomerulus']),
                        ('AL-VA3(R)', ['right VA3 glomerulus']),
                        ('AL-VA3(L)', ['left VA3 glomerulus']),
                        (['AL-VA3(R)', 'AL-VA3(L)'], ['VA3 glomerulus']),
                        ('AL-VA4(R)', ['right VA4 glomerulus']),
                        ('AL-VA4(L)', ['left VA4 glomerulus']),
                        (['AL-VA4(R)', 'AL-VA4(L)'], ['VA4 glomerulus']),
                        ('AL-VA5(R)', ['right VA5 glomerulus']),
                        ('AL-VA5(L)', ['left VA5 glomerulus']),
                        (['AL-VA5(R)', 'AL-VA5(L)'], ['VA5 glomerulus']),
                        ('AL-VA6(R)', ['right VA6 glomerulus']),
                        ('AL-VA6(L)', ['left VA6 glomerulus']),
                        (['AL-VA6(R)', 'AL-VA6(L)'], ['VA6 glomerulus']),
                        ('AL-VA7l(R)', ['right VA7l glomerulus']),
                        ('AL-VA7l(L)', ['left VA7l glomerulus']),
                        (['AL-VA7l(R)', 'AL-VA7l(L)'], ['VA7l glomerulus']),
                        ('AL-VA7m(R)', ['right VA7m glomerulus']),
                        ('AL-VA7m(L)', ['left VA7m glomerulus']),
                        (['AL-VA7m(R)', 'AL-VA7m(L)'], ['VA7m glomerulus']),
                        ('AL-VC1(R)', ['right VC1 glomerulus']),
                        ('AL-VC1(L)', ['left VC1 glomerulus']),
                        (['AL-VC1(R)', 'AL-VC1(L)'], ['VC1 glomerulus']),
                        ('AL-VC2(R)', ['right VC2 glomerulus']),
                        ('AL-VC2(L)', ['left VC2 glomerulus']),
                        (['AL-VC2(R)', 'AL-VC2(L)'], ['VC2 glomerulus']),
                        ('AL-VC3m(R)', ['right VC3m glomerulus']),
                        ('AL-VC3m(L)', ['left VC3m glomerulus']),
                        (['AL-VC3m(R)', 'AL-VC3m(L)'], ['VC3m glomerulus']),
                        ('AL-VC3l(R)', ['right VC3l glomerulus']),
                        ('AL-VC3l(L)', ['left VC3l glomerulus']),
                        (['AL-VC3l(R)', 'AL-VC3l(L)'], ['VC3l glomerulus']),
                        ('AL-VC4(R)', ['right VC4 glomerulus']),
                        ('AL-VC4(L)', ['left VC4 glomerulus']),
                        (['AL-VC4(R)', 'AL-VC4(L)'], ['VC4 glomerulus']),
                        ('AL-VC5(R)', ['right VC5 glomerulus']),
                        ('AL-VC5(L)', ['left VC5 glomerulus']),
                        (['AL-VC5(R)', 'AL-VC5(L)'], ['VC5 glomerulus']),
                        ('AL-VL1(R)', ['right VL1 glomerulus']),
                        ('AL-VL1(L)', ['left VL1 glomerulus']),
                        (['AL-VL1(R)', 'AL-VL1(L)'], ['VL1 glomerulus']),
                        ('AL-VL2a(R)', ['right VL2a glomerulus']),
                        ('AL-VL2a(L)', ['left VL2a glomerulus']),
                        (['AL-VL2a(R)', 'AL-VL2a(L)'], ['VL2a glomerulus']),
                        ('AL-VL2p(R)', ['right VL2p glomerulus']),
                        ('AL-VL2p(L)', ['left VL2p glomerulus']),
                        (['AL-VL2p(R)', 'AL-VL2p(L)'], ['VL2p glomerulus']),
                        ('AL-VM1(R)', ['right VM1 glomerulus']),
                        ('AL-VM1(L)', ['left VM1 glomerulus']),
                        (['AL-VM1(R)', 'AL-VM1(L)'], ['VM1 glomerulus']),
                        ('AL-VM2(R)', ['right VM12glomerulus']),
                        ('AL-VM2(L)', ['left VM2 glomerulus']),
                        (['AL-VM2(R)', 'AL-VM2(L)'], ['VM2 glomerulus']),
                        ('AL-VM3(R)', ['right VM3 glomerulus']),
                        ('AL-VM3(L)', ['left VM3 glomerulus']),
                        (['AL-VM3(R)', 'AL-VM3(L)'], ['VM3 glomerulus']),
                        ('AL-VM4(R)', ['right VM4 glomerulus']),
                        ('AL-VM4(L)', ['left VM4 glomerulus']),
                        (['AL-VM4(R)', 'AL-VM4(L)'], ['VM4 glomerulus']),
                        ('AL-VM5d(R)', ['right VM5d glomerulus']),
                        ('AL-VM5d(L)', ['left VM5d glomerulus']),
                        (['AL-VM5d(R)', 'AL-VM5d(L)'], ['VM5d glomerulus']),
                        ('AL-VM5v(R)', ['right VM5v glomerulus']),
                        ('AL-VM5v(L)', ['left VM5v glomerulus']),
                        (['AL-VM5v(R)', 'AL-VM5v(L)'], ['VM5v glomerulus']),
                        ('AL-VM7d(R)', ['right VM7d glomerulus']),
                        ('AL-VM7d(L)', ['left VM7d glomerulus']),
                        (['AL-VM7d(R)', 'AL-VM7d(L)'], ['VM7d glomerulus']),
                        ('AL-VM7v(R)', ['right VM7v glomerulus']),
                        ('AL-VM7v(L)', ['left VM7v glomerulus']),
                        (['AL-VM7v(R)', 'AL-VM7v(L)'], ['VM7v glomerulus']),
                        ('AL-V(R)', ['right V glomerulus']),
                        ('AL-V(L)', ['left V glomerulus']),
                        (['AL-V(R)', 'AL-V(L)'], ['V glomerulus']),
                        ('AL-VP5(R)', ['right VP5 glomerulus']),
                        ('AL-VP5(L)', ['left VP5 glomerulus']),
                        (['AL-VP5(R)', 'AL-VP5(L)'], ['VP5 glomerulus']),
                        ('AL-VP4(R)', ['right VP4 glomerulus']),
                        ('AL-VP4(L)', ['left VP4 glomerulus']),
                        (['AL-VP4(R)', 'AL-VP4(L)'], ['VP4 glomerulus']),
                        ('AL-VP3(R)', ['right VP3 glomerulus']),
                        ('AL-VP3(L)', ['left VP3 glomerulus']),
                        (['AL-VP3(R)', 'AL-VP3(L)'], ['VP3 glomerulus']),
                        ('AL-VP2(R)', ['right VP2 glomerulus']),
                        ('AL-VP2(L)', ['left VP2 glomerulus']),
                        (['AL-VP2(R)', 'AL-VP2(L)'], ['VP2 glomerulus']),
                        ('AL-VP1m(R)', ['right VP1m glomerulus']),
                        ('AL-VP1m(L)', ['left VP1m glomerulus']),
                        (['AL-VP1m(R)', 'AL-VP1m(L)'], ['VP1m glomerulus']),
                        ('AL-VP1l(R)', ['right VP1l glomerulus']),
                        ('AL-VP1l(L)', ['left VP1l glomerulus']),
                        (['AL-VP1l(R)', 'AL-VP1l(L)'], ['VP1l glomerulus']),
                        ('AL-VP1d(R)', ['right VP1d glomerulus']),
                        ('AL-VP1d(L)', ['left VP1d glomerulus']),
                        (['AL-VP1d(R)', 'AL-VP1d(L)'], ['VP1d glomerulus']),
                        ]

for a, b in arborization_regions:
    for i in range(len(b)):
        b[i] = b[i].lower()

# 'subregion query name': (Class, Instance, Name)
subregions = {
    'right calyx': ('Subregion', '', 'CA(R)'),
    'right ca': ('Subregion', '', 'CA(R)'),
    'ca(r)': ('Subregion', '', 'CA(R)'),
    'ca_r': ('Subregion', '', 'CA(R)'),
    'left calyx': ('Subregion', '', 'CA(L)'),
    'left ca': ('Subregion', '', 'CA(L)'),
    'ca(l)': ('Subregion', '', 'CA(L)'),
    'ca_l': ('Subregion', '', 'CA(L)'),
    'right laca': ('Subregion', '', 'lACA(R)'),
    'laca(r)': ('Subregion', '', 'lACA(R)'),
    'laca_r': ('Subregion', '', 'lACA(R)'),
    'right lateral accessory calyx': ('Subregion', '', 'lACA(R)'),
    'right daca': ('Subregion', '', 'dACA(R)'),
    'daca(r)': ('Subregion', '', 'dACA(R)'),
    'daca_r': ('Subregion', '', 'dACA(R)'),
    'right dorsal accessory calyx': ('Subregion', '', 'dACA(R)'),
    'right vaca': ('Subregion', '', 'vACA(R)'),
    'vaca(r)': ('Subregion', '', 'vACA(R)'),
    'vaca_r': ('Subregion', '', 'vACA(R)'),
    'right ventral accessory calyx': ('Subregion', '', 'vACA(R)'),
    'right pedunculus': ('Subregion', '', 'PED(R)'),
    'right ped': ('Subregion', '', 'PED(R)'),
    'ped(r)': ('Subregion', '', 'PED(R)'),
    'ped_r': ('Subregion', '', 'PED(R)'),
    'right alpha lobe': ('Subregion', '', 'aL(R)'),
    'alpha lobe': ('Subregion', '', ['aL(R)', 'aL(L)']),
    'right alpha1 compartment': ('Subregion', '', 'a1(R)'),
    'right alpha lobe compartment 1': ('Subregion', '', 'a1(R)'),
    'a1(r)': ('Subregion', '', 'a1(R)'),
    'alpha1_r': ('Subregion', '', 'a1(R)'),
    'alpha1': ('Subregion', '', ['a1(R)','a1(L)']),
    'right alpha2 compartment': ('Subregion', '', 'a2(R)'),
    'right alpha lobe compartment 2': ('Subregion', '', 'a2(R)'),
    'a2(r)': ('Subregion', '', 'a2(R)'),
    'alpha2_r': ('Subregion', '', 'a2(R)'),
    'alpha2': ('Subregion', '', ['a2(R)','a2(L)']),
    'right alpha3 compartment': ('Subregion', '', 'a3(R)'),
    'right alpha lobe compartment 3': ('Subregion', '', 'a3(R)'),
    'a3(r)': ('Subregion', '', 'a3(R)'),
    'alpha3_r': ('Subregion', '', 'a3(R)'),
    'alpha3': ('Subregion', '', ['a3(R)','a3(L)']),
    "right alpha prime lobe": ('Subregion', '', "a'L(R)"),
    'alpha prime lobe': ('Subregion', '', ["a'L(R)", "a'L(L)"]),
    "alpha' lobe": ('Subregion', '', ["a'L(R)", "a'L(L)"]),
    "right alpha' lobe": ('Subregion', '', "a'L(R)"),
    "right alpha'1 compartment": ('Subregion', '', "a'1(R)"),
    "right alpha prime lobe compartment 1": ('Subregion', '', "a'1(R)"),
    "right alpha' lobe compartment 1": ('Subregion', '', "a'1(R)"),
    "a'1(r)": ('Subregion', '', "a'1(R)"),
    "alpha'1_r": ('Subregion', '', "a'1(R)"),
    "alpha'1": ('Subregion', '', ["a'1(R)", "a'1(L)"]),
    "right alpha'2 compartment": ('Subregion', '', "a'2(R)"),
    "right alpha prime lobe compartment 2": ('Subregion', '', "a'2(R)"),
    "right alpha' lobe compartment 2": ('Subregion', '', "a'2(R)"),
    "a'2(r)": ('Subregion', '', "a'2(R)"),
    "alpha'2_r": ('Subregion', '', "a'2(R)"),
    "alpha'2": ('Subregion', '', ["a'2(R)", "a'2(L)"]),
    "right alpha'3 compartment": ('Subregion', '', "a'3(R)"),
    "right alpha prime lobe compartment 3": ('Subregion', '', "a'3(R)"),
    "right alpha' lobe compartment 3": ('Subregion', '', "a'3(R)"),
    "a'3(r)": ('Subregion', '', "a'3(R)"),
    "alpha'3_r": ('Subregion', '', "a'3(R)"),
    "alpha'3": ('Subregion', '', ["a'3(R)", "a'3(L)"]),
    'right beta lobe': ('Subregion', '', 'bL(R)'),
    'right beta1 compartment': ('Subregion', '', 'b1(R)'),
    'right beta lobe compartment 1': ('Subregion', '', 'b1(R)'),
    'b1(r)': ('Subregion', '', 'b1(R)'),
    "beta1_r": ('Subregion', '', "b1(R)"),
    "beta1": ('Subregion', '', ["b1(R)", "b1(L)"]),
    'right beta2 compartment': ('Subregion', '', 'b2(R)'),
    'right beta lobe compartment 2': ('Subregion', '', 'b2(R)'),
    'b2(r)': ('Subregion', '', 'b2(R)'),
    "beta2_r": ('Subregion', '', "b2(R)"),
    "beta2": ('Subregion', '', ["b2(R)", "b2(L)"]),
    "right beta prime lobe": ('Subregion', '', "b'L(R)"),
    "right beta' lobe": ('Subregion', '', "b'L(R)"),
    "beta' lobe": ('Subregion', '', ["b'L(R)", "b'L(L)"]),
    "beta prime lobe": ('Subregion', '', ["b'L(R)", "b'L(L)"]),
    "right beta'1 compartment": ('Subregion', '', "b'1(R)"),
    "right beta prime lobe compartment 1": ('Subregion', '', "b'1(R)"),
    "right beta' lobe compartment 1": ('Subregion', '', "b'1(R)"),
    "b'1(r)": ('Subregion', '', "b'1(R)"),
    "beta'1_r": ('Subregion', '', "b'1(R)"),
    "beta'1": ('Subregion', '', ["b'1(R)", "b'1(L)"]),
    "right beta'2 compartment": ('Subregion', '', "b'2(R)"),
    "right beta prime lobe compartment 2": ('Subregion', '', "b'2(R)"),
    "right beta' lobe compartment 2": ('Subregion', '', "b'2(R)"),
    "b'2(r)": ('Subregion', '', "b'2(R)"),
    "beta'2_r": ('Subregion', '', "b'2(R)"),
    "beta'2": ('Subregion', '', ["b'2(R)", "b'2(L)"]),
    'right gamma lobe': ('Subregion', '', 'gL(R)'),
    "gamma lobe": ('Subregion', '', ["gL(R)", "gL(L)"]),
    'right gamma1 compartment': ('Subregion', '', 'g1(R)'),
    'right gamma lobe compartment 1': ('Subregion', '', 'g1(R)'),
    'g1(r)': ('Subregion', '', 'g1(R)'),
    "gamma1_r": ('Subregion', '', "g1(R)"),
    "gamma1": ('Subregion', '', ["g1(R)", "g1(L)"]),
    'right gamma2 compartment': ('Subregion', '', 'g2(R)'),
    'right gamma lobe compartment 2': ('Subregion', '', 'g2(R)'),
    'g2(r)': ('Subregion', '', 'g2(R)'),
    "gamma2_r": ('Subregion', '', "g2(R)"),
    "gamma2": ('Subregion', '', ["g2(R)", "g2(L)"]),
    'right gamma3 compartment': ('Subregion', '', 'g3(R)'),
    'right gamma lobe compartment 3': ('Subregion', '', 'g3(R)'),
    'g3(r)': ('Subregion', '', 'g3(R)'),
    "gamma3_r": ('Subregion', '', "g3(R)"),
    "gamma3": ('Subregion', '', ["g3(R)", "g3(L)"]),
    'right gamma4 compartment': ('Subregion', '', 'g4(R)'),
    'right gamma lobe compartment 4': ('Subregion', '', 'g4(R)'),
    'g4(r)': ('Subregion', '', 'g4(R)'),
    "gamma4_r": ('Subregion', '', "g4(R)"),
    "gamma4": ('Subregion', '', ["g4(R)", "g4(L)"]),
    'right gamma5 compartment': ('Subregion', '', 'g5(R)'),
    'right gamma lobe compartment 5': ('Subregion', '', 'g5(R)'),
    'g5(r)': ('Subregion', '', 'g5(R)'),
    "gamma5_r": ('Subregion', '', "g5(R)"),
    "gamma5": ('Subregion', '', ["g5(R)", "g5(L)"]),
    'ga(r)': ('Subregion', '', 'GA(R)'),
    'right gall': ('Subregion', '', 'GA(R)'),
    'right ga': ('Subregion', '', 'GA(R)'),
    "ga": ('Subregion', '', ["GA(R)", "GA(L)"]),
    "gall": ('Subregion', '', ["GA(R)", "GA(L)"]),
    'fbl1': ('Subregion', '', 'FBl1'),
    'fanshaped body layer 1': ('Subregion', '', 'FBl1'),
    'fb layer 1': ('Subregion', '', 'FBl1'),
    'fbl2': ('Subregion', '', 'FBl2'),
    'fanshaped body layer 2': ('Subregion', '', 'FBl2'),
    'fb layer 2': ('Subregion', '', 'FBl2'),
    'fbl3': ('Subregion', '', 'FBl3'),
    'fanshaped body layer 3': ('Subregion', '', 'FBl3'),
    'fb layer 3': ('Subregion', '', 'FBl3'),
    'fbl4': ('Subregion', '', 'FBl4'),
    'fanshaped body layer 4': ('Subregion', '', 'FBl4'),
    'fb layer 4': ('Subregion', '', 'FBl4'),
    'fbl5': ('Subregion', '', 'FBl5'),
    'fanshaped body layer 5': ('Subregion', '', 'FBl5'),
    'fb layer 5': ('Subregion', '', 'FBl5'),
    'fbl6': ('Subregion', '', 'FBl6'),
    'fanshaped body layer 6': ('Subregion', '', 'FBl6'),
    'fb layer 6': ('Subregion', '', 'FBl6'),
    'fbl7': ('Subregion', '', 'FBl7'),
    'fanshaped body layer 7': ('Subregion', '', 'FBl7'),
    'fb layer 7': ('Subregion', '', 'FBl7'),
    'fbl8': ('Subregion', '', 'FBl8'),
    'fanshaped body layer 8': ('Subregion', '', 'FBl8'),
    'fb layer 8': ('Subregion', '', 'FBl8'),
    'fbl9': ('Subregion', '', 'FBl9'),
    'fanshaped body layer 9': ('Subregion', '', 'FBl9'),
    'fb layer 9': ('Subregion', '', 'FBl9'),
    'ellipsoid body zone r1': ('Subregion', '', 'EBr1'),
    'eb zone r1': ('Subregion', '', 'EBr1'),
    'ebr1': ('Subregion', '', 'EBr1'),
    'ellipsoid body zone r2r4': ('Subregion', '', 'EBr2r4'),
    'eb zone r2r4': ('Subregion', '', 'EBr2r4'),
    'ebr2r4': ('Subregion', '', 'EBr2r4'),
    'ellipsoid body zone r3am': ('Subregion', '', 'EBr3am'),
    'eb zone r3am': ('Subregion', '', 'EBr3am'),
    'ebr3am': ('Subregion', '', 'EBr3am'),
    'ellipsoid body zone r3d': ('Subregion', '', 'EBr3d'),
    'eb zone r3d': ('Subregion', '', 'EBr3d'),
    'ebr3d': ('Subregion', '', 'EBr3d'),
    'ellipsoid body zone r3pw': ('Subregion', '', 'EBr3pw'),
    'eb zone r3pw': ('Subregion', '', 'EBr3pw'),
    'ebr3pw': ('Subregion', '', 'EBr3pw'),
    'ellipsoid body zone r5': ('Subregion', '', 'EBr5'),
    'eb zone r5': ('Subregion', '', 'EBr5'),
    'ebr5': ('Subregion', '', 'EBr5'),
    'ellipsoid body zone r6': ('Subregion', '', 'EBr6'),
    'eb zone r6': ('Subregion', '', 'EBr6'),
    'ebr6': ('Subregion', '', 'EBr6'),
    'pb glomerulus r1': ('Subregion', '', 'PB(R1)'),
    'pb r1': ('Subregion', '', 'PB(R1)'),
    'pbr1': ('Subregion', '', 'PB(R1)'),
    'pb glomerulus r2': ('Subregion', '', 'PB(R2)'),
    'pb r2': ('Subregion', '', 'PB(R2)'),
    'pbr2': ('Subregion', '', 'PB(R2)'),
    'pb glomerulus r3': ('Subregion', '', 'PB(R3)'),
    'pb r3': ('Subregion', '', 'PB(R3)'),
    'pbr3': ('Subregion', '', 'PB(R3)'),
    'pb glomerulus r4': ('Subregion', '', 'PB(R4)'),
    'pb r4': ('Subregion', '', 'PB(R4)'),
    'pbr4': ('Subregion', '', 'PB(R4)'),
    'pb glomerulus r5': ('Subregion', '', 'PB(R5)'),
    'pb r5': ('Subregion', '', 'PB(R5)'),
    'pbr5': ('Subregion', '', 'PB(R5)'),
    'pb glomerulus r6': ('Subregion', '', 'PB(R6)'),
    'pb r6': ('Subregion', '', 'PB(R6)'),
    'pbr6': ('Subregion', '', 'PB(R6)'),
    'pb glomerulus r7': ('Subregion', '', 'PB(R7)'),
    'pb r7': ('Subregion', '', 'PB(R7)'),
    'pbr7': ('Subregion', '', 'PB(R7)'),
    'pb glomerulus r8': ('Subregion', '', 'PB(R8)'),
    'pb r8': ('Subregion', '', 'PB(R8)'),
    'pbr8': ('Subregion', '', 'PB(R8)'),
    'pb glomerulus r9': ('Subregion', '', 'PB(R9)'),
    'pb r9': ('Subregion', '', 'PB(R9)'),
    'pbr9': ('Subregion', '', 'PB(R9)'),
    'pb glomerulus l1': ('Subregion', '', 'PB(L1)'),
    'pb l1': ('Subregion', '', 'PB(L1)'),
    'pbl1': ('Subregion', '', 'PB(L1)'),
    'pb glomerulus l2': ('Subregion', '', 'PB(L2)'),
    'pb l2': ('Subregion', '', 'PB(L2)'),
    'pbl2': ('Subregion', '', 'PB(L2)'),
    'pb glomerulus l3': ('Subregion', '', 'PB(L3)'),
    'pb l3': ('Subregion', '', 'PB(L3)'),
    'pbl3': ('Subregion', '', 'PB(L3)'),
    'pb glomerulus l4': ('Subregion', '', 'PB(L4)'),
    'pb l4': ('Subregion', '', 'PB(L4)'),
    'pbl4': ('Subregion', '', 'PB(L4)'),
    'pb glomerulus l5': ('Subregion', '', 'PB(L5)'),
    'pb l5': ('Subregion', '', 'PB(L5)'),
    'pbl5': ('Subregion', '', 'PB(L5)'),
    'pb glomerulus l6': ('Subregion', '', 'PB(L6)'),
    'pb l6': ('Subregion', '', 'PB(L6)'),
    'pbl6': ('Subregion', '', 'PB(L6)'),
    'pb glomerulus l7': ('Subregion', '', 'PB(L7)'),
    'pb l7': ('Subregion', '', 'PB(L7)'),
    'pbl7': ('Subregion', '', 'PB(L7)'),
    'pb glomerulus l8': ('Subregion', '', 'PB(L8)'),
    'pb l8': ('Subregion', '', 'PB(L8)'),
    'pbl8': ('Subregion', '', 'PB(L8)'),
    'pb glomerulus l9': ('Subregion', '', 'PB(L9)'),
    'pb l9': ('Subregion', '', 'PB(L9)'),
    'pbl9': ('Subregion', '', 'PB(L9)'),
    'right nodulus 1': ('Subregion', '', 'NO1(R)'),
    'right no 1': ('Subregion', '', 'NO1(R)'),
    'no1(r)': ('Subregion', '', 'NO1(R)'),
    'no1_r': ('Subregion', '', 'NO1(R)'),
    "no1": ('Subregion', '', ["NO1(R)", "NO1(L)"]),
    'right nodulus 2': ('Subregion', '', 'NO2(R)'),
    'right no 2': ('Subregion', '', 'NO2(R)'),
    'no2(r)': ('Subregion', '', 'NO2(R)'),
    'no2_r': ('Subregion', '', 'NO2(R)'),
    "no2": ('Subregion', '', ["NO2(R)", "NO2(L)"]),
    'right nodulus 3': ('Subregion', '', 'NO3(R)'),
    'right no 3': ('Subregion', '', 'NO3(R)'),
    'no3(r)': ('Subregion', '', 'NO3(R)'),
    'no3_r': ('Subregion', '', 'NO3(R)'),
    "no3": ('Subregion', '', ["NO3(R)", "NO3(L)"]),
    'left nodulus 1': ('Subregion', '', 'NO1(L)'),
    'left no 1': ('Subregion', '', 'NO1(L)'),
    'no1(l)': ('Subregion', '', 'NO1(L)'),
    'no1_l': ('Subregion', '', 'NO1(L)'),
    'left nodulus 2': ('Subregion', '', 'NO2(L)'),
    'left no 2': ('Subregion', '', 'NO2(L)'),
    'no2(l)': ('Subregion', '', 'NO2(L)'),
    'no2_l': ('Subregion', '', 'NO2(L)'),
    'left nodulus 3': ('Subregion', '', 'NO3(L)'),
    'left no 3': ('Subregion', '', 'NO3(L)'),
    'no3(l)': ('Subregion', '', 'NO3(L)'),
    'no3_l': ('Subregion', '', 'NO3(L)'),
    'right rub': ('Subregion', '', 'RUB(R)'),
    'right rubus': ('Subregion', '', 'RUB(R)'),
    'rub(r)': ('Subregion', '', 'RUB(R)'),
    'rub_r': ('Subregion', '', 'RUB(R)'),
    "rub": ('Subregion', '', ["RUB(R)", "RUB(L)"]),
    "rubus": ('Subregion', '', ["RUB(R)", "RUB(L)"]),
    'right rob': ('Subregion', '', 'ROB(R)'),
    'right round body': ('Subregion', '', 'ROB(R)'),
    "rob": ('Subregion', '', ["ROB(R)", "ROB(L)"]),
    "round body": ('Subregion', '', ["ROB(R)", "ROB(L)"]),
    'rob(r)': ('Subregion', '', 'ROB(R)'),
    'rob_r': ('Subregion', '', 'ROB(R)'),
    'ammc': ('Subregion', '', 'AMMC'),
    'antennal mechanosensory and motor center': ('Subregion', '', 'AMMC'),
    'right da1 glomerulus': ('Subregion', '', 'AL-DA1(R)'),
    'left da1 glomerulus': ('Subregion', '',  'AL-DA1(L)'),
    'da1 glomerulus': ('Subregion', '', ['AL-DA1(R)', 'AL-DA1(L)']),
    'right da2 glomerulus': ('Subregion', '', 'AL-DA2(R)'),
    'left da2 glomerulus': ('Subregion', '', 'AL-DA2(L)'),
    'da2 glomerulus': ('Subregion', '', ['AL-DA2(R)', 'AL-DA2(L)']),
    'right da3 glomerulus': ('Subregion', '', 'AL-DA3(R)'),
    'left da3 glomerulus': ('Subregion', '', 'AL-3(L)'),
    'da3 glomerulus': ('Subregion', '', ['AL-DA3(R)', 'AL-DA3(L)']),
    'right da4l glomerulus': ('Subregion', '', 'AL-DA4l(R)'),
    'left da4l glomerulus': ('Subregion', '', 'AL-DA4l(L)'),
    'da4l glomerulus': ('Subregion', '', ['AL-DA4l(R)', 'AL-DA4l(L)']),
    'right da4m glomerulus': ('Subregion', '', 'AL-DA4m(R)'),
    'left da4m glomerulus': ('Subregion', '', 'AL-DA4m(L)'),
    'da4m glomerulus': ('Subregion', '', ['AL-DA4m(R)', 'AL-DA4m(L)']),
    'right dc1 glomerulus': ('Subregion', '', 'AL-DC1(R)'),
    'left dc1 glomerulus': ('Subregion', '', 'AL-DC1(L)'),
    'dc1 glomerulus': ('Subregion', '', ['AL-DC1(R)', 'AL-DC1(L)']),
    'right dc2 glomerulus': ('Subregion', '', 'AL-DC2(R)'),
    'left dc2 glomerulus': ('Subregion', '', 'AL-DC2(L)'),
    'dc2 glomerulus': ('Subregion', '', ['AL-DC2(R)', 'AL-DC2(L)']),
    'right dc3 glomerulus': ('Subregion', '', 'AL-DC3(R)'),
    'left dc3 glomerulus': ('Subregion', '', 'AL-DC3(L)'),
    'dc3 glomerulus': ('Subregion', '', ['AL-DC3(R)', 'AL-DC3(L)']),
    'right dc4 glomerulus': ('Subregion', '', 'AL-DC4(R)'),
    'left dc4 glomerulus': ('Subregion', '', 'AL-DC4(L)'),
    'dc4 glomerulus': ('Subregion', '', ['AL-DC4(R)', 'AL-DC4(L)']),
    'right dl1 glomerulus': ('Subregion', '', 'AL-DL1(R)'),
    'left dl1 glomerulus': ('Subregion', '', 'AL-DL1(L)'),
    'dl1 glomerulus': ('Subregion', '', ['AL-DL1(R)', 'AL-DL1(L)']),
    'right dl2d glomerulus': ('Subregion', '', 'AL-DL2d(R)'),
    'left dl2d glomerulus': ('Subregion', '', 'AL-DL2d(L)'),
    'dl2d glomerulus': ('Subregion', '', ['AL-DL2d(R)', 'AL-DL2d(L)']),
    'right dl2v glomerulus': ('Subregion', '', 'AL-DL2v(R)'),
    'left dl2v glomerulus': ('Subregion', '', 'AL-DL2v(L)'),
    'dl2v glomerulus': ('Subregion', '', ['AL-DL2v(R)', 'AL-DL2v(L)']),
    'right dl3 glomerulus': ('Subregion', '', 'AL-DL3(R)'),
    'left dl3 glomerulus': ('Subregion', '', 'AL-DL3(L)'),
    'dl3 glomerulus': ('Subregion', '', ['AL-DL3(R)', 'AL-DL3(L)']),
    'right dl4 glomerulus': ('Subregion', '', 'AL-DL4(R)'),
    'left dl4 glomerulus': ('Subregion', '', 'AL-DL4(L)'),
    'dl4 glomerulus': ('Subregion', '', ['AL-DL4(R)', 'AL-DL4(L)']),
    'right dl5 glomerulus': ('Subregion', '', 'AL-DL5(R)'),
    'left dl5 glomerulus': ('Subregion', '', 'AL-DL5(L)'),
    'dl5 glomerulus': ('Subregion', '', ['AL-DL5(R)', 'AL-DL5(L)']),
    'right d glomerulus': ('Subregion', '', 'AL-D(R)'),
    'left d glomerulus': ('Subregion', '', 'AL-D(L)'),
    'd glomerulus': ('Subregion', '', ['AL-D(R)', 'AL-D(L)']),
    'right dm1 glomerulus': ('Subregion', '', 'AL-DM1(R)'),
    'left dm1 glomerulus': ('Subregion', '', 'AL-DM1(L)'),
    'dm1 glomerulus': ('Subregion', '', ['AL-DM1(R)', 'AL-DM1(L)']),
    'right dm2 glomerulus': ('Subregion', '', 'AL-DM2(R)'),
    'left dm2 glomerulus': ('Subregion', '', 'AL-DM2(L)'),
    'dm2 glomerulus': ('Subregion', '', ['AL-DM2(R)', 'AL-DM2(L)']),
    'right dm3 glomerulus': ('Subregion', '', 'AL-DM3(R)'),
    'left dm3 glomerulus': ('Subregion', '', 'AL-DM3(L)'),
    'dm3 glomerulus': ('Subregion', '', ['AL-DM3(R)', 'AL-DM3(L)']),
    'right dm4 glomerulus': ('Subregion', '', 'AL-DM4(R)'),
    'left dm4 glomerulus': ('Subregion', '', 'AL-DM4(L)'),
    'dm4 glomerulus': ('Subregion', '', ['AL-DM4(R)', 'AL-DM4(L)']),
    'right dm5 glomerulus': ('Subregion', '', 'AL-DM5(R)'),
    'left dm5 glomerulus': ('Subregion', '', 'AL-DM5(L)'),
    'dm5 glomerulus': ('Subregion', '', ['AL-DM5(R)', 'AL-DM5(L)']),
    'right dm6 glomerulus': ('Subregion', '', 'AL-DM6(R)'),
    'left dm6 glomerulus': ('Subregion', '', 'AL-DM6(L)'),
    'dm6 glomerulus': ('Subregion', '', ['AL-DM6(R)', 'AL-DM6(L)']),
    'right dp1l glomerulus': ('Subregion', '', 'AL-DP1l(R)'),
    'left dp1l glomerulus': ('Subregion', '', 'AL-DP1l(L)'),
    'dp1l glomerulus': ('Subregion', '', ['AL-DP1l(R)', 'AL-DP1l(L)']),
    'right dp1m glomerulus': ('Subregion', '', 'AL-DP1m(R)'),
    'left dp1m glomerulus': ('Subregion', '', 'AL-DP1m(L)'),
    'dp1m glomerulus': ('Subregion', '', ['AL-DP1m(R)', 'AL-DP1m(L)']),
    'right va1d glomerulus': ('Subregion', '', 'AL-VA1d(R)'),
    'left va1d glomerulus': ('Subregion', '', 'AL-VA1d(L)'),
    'va1d glomerulus': ('Subregion', '', ['AL-VA1d(R)', 'AL-VA1d(L)']),
    'right va1v glomerulus': ('Subregion', '', 'AL-VA1v(R)'),
    'left va1v glomerulus': ('Subregion', '', 'AL-VA1v(L)'),
    'va1v glomerulus': ('Subregion', '', ['AL-VA1v(R)', 'AL-VA1v(L)']),
    'right va2 glomerulus': ('Subregion', '', 'AL-VA2(R)'),
    'left va2 glomerulus': ('Subregion', '', 'AL-VA2(L)'),
    'va2 glomerulus': ('Subregion', '', ['AL-VA2(R)', 'AL-VA2(L)']),
    'right va3 glomerulus': ('Subregion', '', 'AL-VA3(R)'),
    'left va3 glomerulus': ('Subregion', '', 'AL-VA3(L)'),
    'va3 glomerulus': ('Subregion', '', ['AL-VA3(R)', 'AL-VA3(L)']),
    'right va4 glomerulus': ('Subregion', '', 'AL-VA4(R)'),
    'left va4 glomerulus': ('Subregion', '', 'AL-VA4(L)'),
    'va4 glomerulus': ('Subregion', '', ['AL-VA4(R)', 'AL-VA4(L)']),
    'right va5 glomerulus': ('Subregion', '', 'AL-VA5(R)'),
    'left va5 glomerulus': ('Subregion', '', 'AL-VA5(L)'),
    'va5 glomerulus': ('Subregion', '', ['AL-VA5(R)', 'AL-VA5(L)']),
    'right va6 glomerulus': ('Subregion', '', 'AL-VA6(R)'),
    'left va6 glomerulus': ('Subregion', '', 'AL-VA6(L)'),
    'va6 glomerulus': ('Subregion', '', ['AL-VA6(R)', 'AL-VA6(L)']),
    'right va7l glomerulus': ('Subregion', '', 'AL-VA7l(R)'),
    'left va7l glomerulus': ('Subregion', '', 'AL-VA7l(L)'),
    'va7l glomerulus': ('Subregion', '', ['AL-VA7l(R)', 'AL-VA7l(L)']),
    'right va7m glomerulus': ('Subregion', '', 'AL-VA7m(R)'),
    'left va7m glomerulus': ('Subregion', '', 'AL-VA7m(L)'),
    'va7m glomerulus': ('Subregion', '', ['AL-VA7m(R)', 'AL-VA7m(L)']),
    'right vc1 glomerulus': ('Subregion', '', 'AL-VC1(R)'),
    'left vc1 glomerulus': ('Subregion', '', 'AL-VC1(L)'),
    'vc1 glomerulus': ('Subregion', '', ['AL-VC1(R)', 'AL-VC1(L)']),
    'right vc2 glomerulus': ('Subregion', '', 'AL-VC2(R)'),
    'left vc2 glomerulus': ('Subregion', '', 'AL-VC2(L)'),
    'vc2 glomerulus': ('Subregion', '', ['AL-VC2(R)', 'AL-VC2(L)']),
    'right vc3l glomerulus': ('Subregion', '', 'AL-VC3l(R)'),
    'left vc3l glomerulus': ('Subregion', '', 'AL-VC3l(L)'),
    'vc3l glomerulus': ('Subregion', '', ['AL-VC3l(R)', 'AL-VC3l(L)']),
    'right vc3m glomerulus': ('Subregion', '', 'AL-VC3m(R)'),
    'left vc3m glomerulus': ('Subregion', '', 'AL-VC3m(L)'),
    'vc3m glomerulus': ('Subregion', '', ['AL-VC3m(R)', 'AL-VC3m(L)']),
    'right vc4 glomerulus': ('Subregion', '', 'AL-VC4(R)'),
    'left vc4 glomerulus': ('Subregion', '', 'AL-VC4(L)'),
    'vc4 glomerulus': ('Subregion', '', ['AL-VC4(R)', 'AL-VC4(L)']),
    'right vc5 glomerulus': ('Subregion', '', 'AL-VC5(R)'),
    'left vc5 glomerulus': ('Subregion', '', 'AL-VC5(L)'),
    'vc5 glomerulus': ('Subregion', '', ['AL-VC5(R)', 'AL-VC5(L)']),
    'right vl1 glomerulus': ('Subregion', '', 'AL-VL1(R)'),
    'left vl1 glomerulus': ('Subregion', '', 'AL-VL1(L)'),
    'vl1 glomerulus': ('Subregion', '', ['AL-VL1(R)', 'AL-VL1(L)']),
    'right vl2a glomerulus': ('Subregion', '', 'AL-VL2a(R)'),
    'left vl2a glomerulus': ('Subregion', '', 'AL-VL2a(L)'),
    'vl2a glomerulus': ('Subregion', '', ['AL-VL2a(R)', 'AL-VL2a(L)']),
    'right vl2p glomerulus': ('Subregion', '', 'AL-VL2p(R)'),
    'left vl2p glomerulus': ('Subregion', '', 'AL-VL2p(L)'),
    'vl2p glomerulus': ('Subregion', '', ['AL-VL2p(R)', 'AL-VL2p(L)']),
    'right vm1 glomerulus': ('Subregion', '', 'AL-VM1(R)'),
    'left vm1 glomerulus': ('Subregion', '', 'AL-VM1(L)'),
    'vm1 glomerulus': ('Subregion', '', ['AL-VM1(R)', 'AL-VM1(L)']),
    'right vm2 glomerulus': ('Subregion', '', 'AL-VM2(R)'),
    'left vm2 glomerulus': ('Subregion', '', 'AL-VM2(L)'),
    'vm2 glomerulus': ('Subregion', '', ['AL-VM2(R)', 'AL-VM2(L)']),
    'right vm3 glomerulus': ('Subregion', '', 'AL-VM3(R)'),
    'left vm3 glomerulus': ('Subregion', '', 'AL-VM3(L)'),
    'vm3 glomerulus': ('Subregion', '', ['AL-VM3(R)', 'AL-VM3(L)']),
    'right vm4 glomerulus': ('Subregion', '', 'AL-VM4(R)'),
    'left vm4 glomerulus': ('Subregion', '', 'AL-VM4(L)'),
    'vm4 glomerulus': ('Subregion', '', ['AL-VM4(R)', 'AL-VM4(L)']),
    'right vm5d glomerulus': ('Subregion', '', 'AL-VM5d(R)'),
    'left vm5d glomerulus': ('Subregion', '', 'AL-VM5d(L)'),
    'vm5d glomerulus': ('Subregion', '', ['AL-VM5d(R)', 'AL-VM5d(L)']),
    'right vm5v glomerulus': ('Subregion', '', 'AL-VM5v(R)'),
    'left vm5v glomerulus': ('Subregion', '', 'AL-VM5v(L)'),
    'vm5v glomerulus': ('Subregion', '', ['AL-VM5v(R)', 'AL-VM5v(L)']),
    'right vm7d glomerulus': ('Subregion', '', 'AL-VM7d(R)'),
    'left vm7d glomerulus': ('Subregion', '', 'AL-VM7d(L)'),
    'vm7d glomerulus': ('Subregion', '', ['AL-VM7d(R)', 'AL-VM7d(L)']),
    'right vm7v glomerulus': ('Subregion', '', 'AL-VM7v(R)'),
    'left vm7v glomerulus': ('Subregion', '', 'AL-VM7v(L)'),
    'vm7v glomerulus': ('Subregion', '', ['AL-VM7v(R)', 'AL-VM7v(L)']),
    'right v glomerulus': ('Subregion', '', 'AL-V(R)'),
    'left v glomerulus': ('Subregion', '', 'AL-V(L)'),
    'v glomerulus': ('Subregion', '', ['AL-V(R)', 'AL-V(L)']),
    'right vp5 glomerulus': ('Subregion', '', 'AL-VP5(R)'),
    'left vp5 glomerulus': ('Subregion', '', 'AL-VP5(L)'),
    'vp5 glomerulus': ('Subregion', '', ['AL-VP5(R)', 'AL-VP5(L)']),
    'right vp4 glomerulus': ('Subregion', '', 'AL-VP4(R)'),
    'left vp4 glomerulus': ('Subregion', '', 'AL-VP4(L)'),
    'vp4 glomerulus': ('Subregion', '', ['AL-VP4(R)', 'AL-VP4(L)']),
    'right vp3 glomerulus': ('Subregion', '', 'AL-VP3(R)'),
    'left vp3 glomerulus': ('Subregion', '', 'AL-VP3(L)'),
    'vp3 glomerulus': ('Subregion', '', ['AL-VP3(R)', 'AL-VP3(L)']),
    'right vp2 glomerulus': ('Subregion', '', 'AL-VP2(R)'),
    'left vp2 glomerulus': ('Subregion', '', 'AL-VP2(L)'),
    'vp2 glomerulus': ('Subregion', '', ['AL-VP2(R)', 'AL-VP2(L)']),
    'right vp1m glomerulus': ('Subregion', '', 'AL-VP1m(R)'),
    'left vp1m glomerulus': ('Subregion', '', 'AL-VP1m(L)'),
    'vp1m glomerulus': ('Subregion', '', ['AL-VP1m(R)', 'AL-VP1m(L)']),
    'right vp1l glomerulus': ('Subregion', '', 'AL-VP1l(R)'),
    'left vp1l glomerulus': ('Subregion', '', 'AL-VP1l(L)'),
    'vp1l glomerulus': ('Subregion', '', ['AL-VP1l(R)', 'AL-VP1l(L)']),
    'right vp1d glomerulus': ('Subregion', '', 'AL-VP1d(R)'),
    'left vp1d glomerulus': ('Subregion', '', 'AL-VP1d(L)'),
    'vp1d glomerulus': ('Subregion', '', ['AL-VP1d(R)', 'AL-VP1d(L)']),
}

subregions = {k.lower(): v for k, v in subregions.items()}

path = pathlib.Path(__file__).parent.resolve()
with open('{}/neuron_types.json'.format(path), 'r') as f:
    all_types = json.load(f)

neuron_types = {k.lower().replace('+', ''): "/r(?i){}[^0-9a-zA-Z](.*)".format(k.split('(')[0].replace('+', '\\\+')) for k in all_types}
subtypes = {}
for n in all_types:
    if len(n.split('_')) > 1:
        sub_names = n.split('_')
        if len(sub_names[-1]) == 1:
            name = '_'.join(sub_names[:-1])
            if name not in subtypes:
                subtypes[name] = []
            subtypes[name].append(sub_names[-1])
neuron_types.update({k.lower().replace('+', ''): "/r(?i){}_({})[^0-9a-zA-Z](.*)".format(k.replace('+', '\\\+'), '|'.join(v))  for k, v in subtypes.items()})

neuron_types.update({
    'osn':'/r(.*)ORN(.*)',
    'orn':'/r(.*)ORN(.*)',
    'olfactory sensory neurons':'/r(.*)ORN(.*)',
    'olfactory sensory neuron':'/r(.*)ORN(.*)',
    'olfactory receptor neuron':'/r(.*)ORN(.*)',
    'olfactory receptor neurons':'/r(.*)ORN(.*)',
     # 'pn':['PN','mPN'],
    'pn': '/r(.*)(?!L)PN(.*)',
    'upn': "/r(D|V)(.*)_(m|v|ml|l|lv|ad|il|l2)PN(.*)",
    'uniglomerular pn': "/r(D|V)(.*)_(m|v|ml|l|lv|ad|il|l2)PN(.*)",
    'mpn': '/rM_(.*)PN(.*)',
    'multipn': '/rM_(.*)PN(.*)',
    'mpns': '/rM_(.*)PN(.*)',
    'multiglomerular pn': '/rM_(.*)PN(.*)',
    'ln': '/r((l[^-]*|v(.*)|i(.*))LN(.*)|LN(_|[^dO]*_)(.*)[0-9]+)',
    'alln': '/r((l[^-]*|v(.*)|i(.*))LN(.*)|LN(_|[^dO]*_)(.*)[0-9]+)',
    'kenyon cells':'/rKC(.*)','kc':'/rKC(.*)','kenyon':'/rKC(.*)','kcs':'/rKC(.*)',
    'alpha beta kc': '/rKCab(.*)',
    'ab kc': '/rKCab(.*)',
    "alpha' beta' kc": "/rKCa'b'(.*)",
    "a'b' kc": "/rKCa'b'(.*)",
    "gamma kc": "/rKCg(.*)",
    "g kc": "/rKCg(.*)",
    'mbon': '/rMBON(.*)',
    'mushroom body output neurons': '/r(.*)MBON(.*)',
    'apl': '/r(.*)APL(.*)R_1',
    'apls': '/r(.*)APL(.*)',
    'dan': '/r(PPL|PAM)(.*)',
    'ppl dan': '/rPPL(.*)',
    'pam dan': '/rPAM(.*)',
    'lc': '/rlc(.*)',
    'lobula columnar': '/rlc(.*)',
    'lplc': '/rlplc(.*)',
    'lobula complex columnar': '/rlplc(.*)',
    'tubu': '/rTuBu(.*)',
    'mc': '/rMC(.*)',
    'lt': '/rLT(.*)',
    'lobula tangential': '/rLT(.*)',
    'lptc': '/rLPTC(.*)',
    'gln': '/rGLN(.*)',
    'all': '/r(.*)'
})

"""
neuron_types.update({
    'lc{}'.format(i): '/rLC{}[^0-9](.*)'.format(i) for i in range(1,41)
})
neuron_types.update({
    'lplc{}'.format(i): '/rLPLC{}[^0-9](.*)'.format(i) for i in range(1,11)
})
neuron_types.update({
    'mbon{}'.format(str(i).zfill(2)): '/rMBON{}[^0-9](.*)'.format(str(i).zfill(2)) for i in range(1,41)
})
neuron_types.update({
    'pam{}'.format(str(i).zfill(2)): '/rPAM{}[^0-9](.*)'.format(str(i).zfill(2)) for i in range(1, 41)
})
neuron_types.update({
    'ppl{}'.format(str(i).zfill(3)): '/rPPL{}[^0-9](.*)'.format(str(i).zfill(2)) for i in range(1, 205)
})
neuron_types.update({
    'tubu{}'.format(str(i).zfill(2)): '/rTuBu{}[^0-9](.*)'.format(str(i).zfill(2)) for i in range(1, 11)
})
neuron_types.update({
    'exr{}_ring'.format(i): '/rExR{}[^0-9](.*)ring(.*)'.format(i) for i in range(1, 10)
})
neuron_types.update({
    'r{}_ring'.format(i): '/rR{}[^0-9](.*)ring(.*)'.format(i) for i in range(1, 10)
})
neuron_types.update({
    'r1_a_ring': '/rR1_a(.*)ring(.*)',
    'r1_b_ring': '/rR1_b(.*)ring(.*)',
    'r2_a_ring': '/rR2_a(.*)ring(.*)',
    'r2_b_ring': '/rR2_b(.*)ring(.*)',
    'r2_a_ring': '/rR2_a(.*)ring(.*)',
    'r2_a_ring': '/rR2_a(.*)ring(.*)',
    'r3a_ring': '/rR3a(.*)ring(.*)',
    'r3a_a_ring': '/rR3a_a(.*)ring(.*)',
    'r3a_b_ring': '/rR3a_b(.*)ring(.*)',
    'r3a_c_ring': '/rR3a_c(.*)ring(.*)',
    'r3d_ring': '/rR3d(.*)ring(.*)',
    'r3d_a_ring': '/rR3d_a(.*)ring(.*)',
    'r3d_b_ring': '/rR3d_b(.*)ring(.*)',
    'r3d_c_ring': '/rR3d_c(.*)ring(.*)',
    'r3m_ring': '/rR3m(.*)ring(.*)',
    'r3p_ring': '/rR3p(.*)ring(.*)',
    'r3p_a_ring': '/rR3p_a(.*)ring(.*)',
    'r3p_b_ring': '/rR3p_b(.*)ring(.*)',
    'r3w_ring': '/rR3w(.*)ring(.*)',
    'r3w_a_ring': '/rR3w_a(.*)ring(.*)',
    'r3w_b_ring': '/rR3w_b(.*)ring(.*)',
    'r3w_c_ring': '/rR3w_c(.*)ring(.*)',
    'r4d_ring': '/rR4d(.*)ring(.*)',
    'r4d_a_ring': '/rR4d_a(.*)ring(.*)',
    'r4d_b_ring': '/rR4d_b(.*)ring(.*)',
    'r4m_ring': '/rR4m(.*)ring(.*)',
})
neuron_types.update({
    'mc{}'.format(i): '/rMC{}[^0-9](.*)'.format(i) for i in range(61,67)
})
neuron_types.update({
    'lt{}'.format(i): '/rLT{}[^0-9](.*)'.format(i) for i in range(1,60)
})
"""

neuron_types['all'] = '/r(.*)'

neuron_types.update({'regex{}'.format(i): 'regex{}'.format(i) for i in range(100)})
